apiVersion: v1
kind: Pod
metadata:
 name: kata
spec:
  containers:
  - name: kata
    image: busybox
    securityContext: 
      privileged: true
    command: ["sh"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
        #    volumeDevices:
        #      - name: vol-pvc-blk-2
        #        devicePath: /dev/xda
    volumeMounts:
      - name: vol-pvc-da-1
        mountPath: /configs-1
        readOnly: true
      - name: vol-pvc-da-2
        mountPath: /configs-2
      - name: identity-certs
        mountPath: /certs
  runtimeClassName: kata-clh
  volumes:
  - name: identity-certs
    emptyDir: {}
  - name: vol-pvc-blk-2
    persistentVolumeClaim:
      claimName: pvc-blk-2
  - name: vol-pvc-da-1
    persistentVolumeClaim:
      claimName: pvc-da-1
  - name: vol-pvc-da-2
    persistentVolumeClaim:
      claimName: pvc-da-2
